-- ============================================================================
-- Online Banking System - Seed Data Fixture (DML)
-- Contains:
--   1. System Configuration Settings (12 entries)
--   2. 1 Administrator User
--   3. 3 Retail Customer Users
--   4. 4 Bank Accounts (Savings and Current) with Starting Balances
--
-- Password Hashing Notice:
--   All password hashes below are genuine BCrypt hashes (engine: at.favre.lib:bcrypt,
--   cost factor: 10, version: $2a$) generated using com.bank.util.PasswordHashTool.
--   Plaintext credentials:
--     - Admin account:     "AdminPass123!"
--     - Customer accounts:  "CustomerPass123!"
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. System Settings Seed Data
-- ----------------------------------------------------------------------------
INSERT INTO system_settings (setting_key, setting_value, description) VALUES
('transfer.per_txn_limit',      '50000.00',  'Maximum allowed value for a single fund transfer in INR'),
('transfer.daily_limit',        '100000.00', 'Maximum cumulative debit transfer amount per account per day in INR'),
('savings.min_balance',         '500.00',    'Mandatory minimum balance for Savings Accounts in INR'),
('savings.interest_rate',       '3.50',      'Annual interest percentage credited to Savings Accounts (% p.a.)'),
('current.max_overdraft',       '100000.00', 'Maximum ceiling for configurable Current Account overdraft limit in INR'),
('loan.interest_rate',          '8.50',      'Standard annual interest rate applied to retail personal loans (% p.a.)'),
('fd.interest_rate',            '6.50',      'Annualized return rate applied to Fixed Deposits (% p.a.)'),
('fraud.high_amount_threshold', '100000.00', 'Transfer threshold triggering high-value fraud review in INR'),
('fraud.velocity_count',        '5',         'Maximum transfers allowed in window before triggering velocity alert'),
('fraud.velocity_minutes',      '10',        'Time window (minutes) evaluated for transfer velocity checks'),
('session.timeout_minutes',     '15',        'Inactive HTTP session timeout period in minutes'),
('maintenance.mode',            'false',     'When true, customer login is suspended with a maintenance notice')
ON DUPLICATE KEY UPDATE 
    setting_value = VALUES(setting_value),
    description   = VALUES(description);

-- ----------------------------------------------------------------------------
-- 2. Administrator User
-- Plaintext Password: AdminPass123!
-- Generated by: com.bank.util.PasswordHashTool
-- BCrypt Hash: $2a$10$wuPl6h9I4h9DNNMzaMriC.P5h9BKz6LeEXnnqvOKt0dJ4.4PvJN/C
-- ----------------------------------------------------------------------------
INSERT INTO users (user_id, full_name, email, phone, address, password_hash, role, status, failed_attempts) VALUES
(1, 'System Administrator', 'admin@bank.com', '9876543210', 'Head Office, 100 Financial District, Mumbai, MH',
 '$2a$10$wuPl6h9I4h9DNNMzaMriC.P5h9BKz6LeEXnnqvOKt0dJ4.4PvJN/C',
 'ADMIN', 'ACTIVE', 0)
ON DUPLICATE KEY UPDATE
    full_name = VALUES(full_name),
    phone     = VALUES(phone),
    address   = VALUES(address);

-- ----------------------------------------------------------------------------
-- 3. Customer Users (3 Retail Customers)
-- Plaintext Password for all 3 customers: CustomerPass123!
-- Generated by: com.bank.util.PasswordHashTool (each row holds a unique salt)
--
-- Customer 1 (user_id = 2):
--   Email: rahul.sharma@example.com
--   Hash:  $2a$10$QDHFuxfmTLx8mAlofdakfuKqD.MoCwDQ9bY0XJIASvWDq7zIzbY66
--
-- Customer 2 (user_id = 3):
--   Email: priya.patel@example.com
--   Hash:  $2a$10$e8nwObhojGMAbrCXrtdI7Ots9uAt80jiOerhIBauV5lFaZZpAUb4a
--
-- Customer 3 (user_id = 4):
--   Email: amit.verma@example.com
--   Hash:  $2a$10$vBQFSAr9J6dIjsGCJse2he2PQdm7H8SAC34LK1Z8UGV7dJwsgQiVO
-- ----------------------------------------------------------------------------
INSERT INTO users (user_id, full_name, email, phone, address, password_hash, role, status, failed_attempts) VALUES
(2, 'Rahul Sharma', 'rahul.sharma@example.com', '9811122233', '42 Connaught Place, New Delhi, DL',
 '$2a$10$QDHFuxfmTLx8mAlofdakfuKqD.MoCwDQ9bY0XJIASvWDq7zIzbY66',
 'CUSTOMER', 'ACTIVE', 0),

(3, 'Priya Patel', 'priya.patel@example.com', '9822233344', '15 Navrangpura, Ahmedabad, GJ',
 '$2a$10$e8nwObhojGMAbrCXrtdI7Ots9uAt80jiOerhIBauV5lFaZZpAUb4a',
 'CUSTOMER', 'ACTIVE', 0),

(4, 'Amit Verma', 'amit.verma@example.com', '9833344455', '88 Indiranagar 100 Feet Rd, Bengaluru, KA',
 '$2a$10$vBQFSAr9J6dIjsGCJse2he2PQdm7H8SAC34LK1Z8UGV7dJwsgQiVO',
 'CUSTOMER', 'ACTIVE', 0)
ON DUPLICATE KEY UPDATE
    full_name = VALUES(full_name),
    phone     = VALUES(phone),
    address   = VALUES(address);

-- ----------------------------------------------------------------------------
-- 4. Bank Accounts (4 Accounts with Starting Balances)
-- All accounts have 12-digit numbers, DECIMAL(15,2) currency representation.
--
-- Account 1: 100000000001 (Rahul Sharma - Savings, ₹25,000.00)
-- Account 2: 100000000002 (Rahul Sharma - Current, ₹50,000.00, Overdraft ₹10,000.00)
-- Account 3: 100000000003 (Priya Patel - Savings, ₹75,000.00)
-- Account 4: 100000000004 (Amit Verma  - Savings, ₹10,000.00)
-- ----------------------------------------------------------------------------
INSERT INTO accounts (account_no, user_id, account_type, balance, overdraft_limit, status) VALUES
('100000000001', 2, 'SAVINGS', 25000.00,     0.00, 'ACTIVE'),
('100000000002', 2, 'CURRENT', 50000.00, 10000.00, 'ACTIVE'),
('100000000003', 3, 'SAVINGS', 75000.00,     0.00, 'ACTIVE'),
('100000000004', 4, 'SAVINGS', 10000.00,     0.00, 'ACTIVE')
ON DUPLICATE KEY UPDATE
    balance         = VALUES(balance),
    overdraft_limit = VALUES(overdraft_limit),
    status          = VALUES(status);
